const express = require("express");

const empleadosController = require("../controllers/empleados.controller");
const authMiddleware = require("../middlewares/auth.middleware");
const {
  uploadEmpleadoDocumento,
  uploadGradoAcademicoAdjunto,
  uploadDiplomadoAdjunto,
  uploadLogroRelevanteAdjunto
} = require("../middlewares/upload.middleware");

const router = express.Router();

router.get("/archivo-preview", empleadosController.previewArchivoEmpleado);
router.get(
  "/:empCod/estado-actualizacion/:tipoEmpleado",
  empleadosController.obtenerEstadoActualizacion
);

router.use(authMiddleware);

router.get("/", empleadosController.listarColaboradores);
router.get("/completos", empleadosController.listarColaboradoresCompletos);
router.post(
  "/:empCod/inicializar",
  empleadosController.inicializarFormularioEmpleado
);
router.get("/:empCod/formulario", empleadosController.obtenerFormularioEmpleado);
router.get("/:empCod/expediente", empleadosController.obtenerExpedienteEmpleado);
router.patch(
  "/:empCod/informacion-personal",
  empleadosController.actualizarInformacionPersonal
);
router.get("/:empCod/hijos", empleadosController.listarHijosEmpleado);
router.post("/:empCod/hijos", empleadosController.crearHijoEmpleado);
router.patch(
  "/:empCod/hijos/:idEmpleadoHijo",
  empleadosController.actualizarHijoEmpleado
);
router.delete(
  "/:empCod/hijos/:idEmpleadoHijo",
  empleadosController.eliminarHijoEmpleado
);
router.post(
  "/:empCod/documentos/:tipoDocumento",
  uploadEmpleadoDocumento.single("archivo"),
  empleadosController.subirDocumentoEmpleado
);
router.get(
  "/:empCod/grados-academicos",
  empleadosController.listarGradosAcademicos
);
router.post(
  "/:empCod/grados-academicos",
  uploadGradoAcademicoAdjunto.single("archivo"),
  empleadosController.crearGradoAcademico
);
router.patch(
  "/:empCod/grados-academicos/:idEmpleadoGradoAcademico",
  uploadGradoAcademicoAdjunto.single("archivo"),
  empleadosController.actualizarGradoAcademico
);
router.delete(
  "/:empCod/grados-academicos/:idEmpleadoGradoAcademico",
  empleadosController.eliminarGradoAcademico
);
router.get(
  "/:empCod/experiencias-profesionales",
  empleadosController.listarExperienciasProfesionales
);
router.post(
  "/:empCod/experiencias-profesionales",
  empleadosController.crearExperienciaProfesional
);
router.patch(
  "/:empCod/experiencias-profesionales/:idEmpleadoExperienciaProfesional",
  empleadosController.actualizarExperienciaProfesional
);
router.delete(
  "/:empCod/experiencias-profesionales/:idEmpleadoExperienciaProfesional",
  empleadosController.eliminarExperienciaProfesional
);
router.get("/:empCod/diplomados", empleadosController.listarDiplomados);
router.post(
  "/:empCod/diplomados",
  uploadDiplomadoAdjunto.single("archivo"),
  empleadosController.crearDiplomado
);
router.patch(
  "/:empCod/diplomados/:idEmpleadoDiplomado",
  uploadDiplomadoAdjunto.single("archivo"),
  empleadosController.actualizarDiplomado
);
router.delete(
  "/:empCod/diplomados/:idEmpleadoDiplomado",
  empleadosController.eliminarDiplomado
);
router.get(
  "/:empCod/experiencias-docentes",
  empleadosController.listarExperienciasDocentes
);
router.post(
  "/:empCod/experiencias-docentes",
  empleadosController.crearExperienciaDocente
);
router.patch(
  "/:empCod/experiencias-docentes/:idEmpleadoExperienciaDocente",
  empleadosController.actualizarExperienciaDocente
);
router.delete(
  "/:empCod/experiencias-docentes/:idEmpleadoExperienciaDocente",
  empleadosController.eliminarExperienciaDocente
);
router.get("/:empCod/logros-relevantes", empleadosController.listarLogrosRelevantes);
router.post(
  "/:empCod/logros-relevantes",
  uploadLogroRelevanteAdjunto.single("archivo"),
  empleadosController.crearLogroRelevante
);
router.patch(
  "/:empCod/logros-relevantes/:idEmpleadoLogroRelevante",
  uploadLogroRelevanteAdjunto.single("archivo"),
  empleadosController.actualizarLogroRelevante
);
router.delete(
  "/:empCod/logros-relevantes/:idEmpleadoLogroRelevante",
  empleadosController.eliminarLogroRelevante
);
router.get(
  "/:empCod/disenios-curriculares",
  empleadosController.listarDiseniosCurriculares
);
router.post(
  "/:empCod/disenios-curriculares",
  empleadosController.crearDisenioCurricular
);
router.patch(
  "/:empCod/disenios-curriculares/:idEmpleadoDisenioCurricular",
  empleadosController.actualizarDisenioCurricular
);
router.delete(
  "/:empCod/disenios-curriculares/:idEmpleadoDisenioCurricular",
  empleadosController.eliminarDisenioCurricular
);
router.get(
  "/:empCod/conocimientos-clave",
  empleadosController.listarConocimientosClave
);
router.post(
  "/:empCod/conocimientos-clave",
  empleadosController.crearConocimientoClave
);
router.patch(
  "/:empCod/conocimientos-clave/:idEmpleadoConocimientoClave",
  empleadosController.actualizarConocimientoClave
);
router.delete(
  "/:empCod/conocimientos-clave/:idEmpleadoConocimientoClave",
  empleadosController.eliminarConocimientoClave
);
router.get(
  "/:empCod/habilidades-relevantes",
  empleadosController.listarHabilidadesRelevantes
);
router.post(
  "/:empCod/habilidades-relevantes",
  empleadosController.crearHabilidadRelevante
);
router.patch(
  "/:empCod/habilidades-relevantes/:idEmpleadoHabilidadRelevante",
  empleadosController.actualizarHabilidadRelevante
);
router.delete(
  "/:empCod/habilidades-relevantes/:idEmpleadoHabilidadRelevante",
  empleadosController.eliminarHabilidadRelevante
);
router.get(
  "/:empCod/proyectos-experiencia",
  empleadosController.listarProyectosExperiencia
);
router.post(
  "/:empCod/proyectos-experiencia",
  empleadosController.crearProyectoExperiencia
);
router.patch(
  "/:empCod/proyectos-experiencia/:idEmpleadoProyectoExperiencia",
  empleadosController.actualizarProyectoExperiencia
);
router.delete(
  "/:empCod/proyectos-experiencia/:idEmpleadoProyectoExperiencia",
  empleadosController.eliminarProyectoExperiencia
);
router.get(
  "/:empCod/experiencias-sector-productivo",
  empleadosController.listarExperienciasSectorProductivo
);
router.post(
  "/:empCod/experiencias-sector-productivo",
  empleadosController.crearExperienciaSectorProductivo
);
router.patch(
  "/:empCod/experiencias-sector-productivo/:idEmpleadoExperienciaSectorProductivo",
  empleadosController.actualizarExperienciaSectorProductivo
);
router.delete(
  "/:empCod/experiencias-sector-productivo/:idEmpleadoExperienciaSectorProductivo",
  empleadosController.eliminarExperienciaSectorProductivo
);
router.get(
  "/:empCod/vinculos-industria",
  empleadosController.listarVinculosIndustria
);
router.post(
  "/:empCod/vinculos-industria",
  empleadosController.crearVinculoIndustria
);
router.patch(
  "/:empCod/vinculos-industria/:idEmpleadoVinculoIndustria",
  empleadosController.actualizarVinculoIndustria
);
router.delete(
  "/:empCod/vinculos-industria/:idEmpleadoVinculoIndustria",
  empleadosController.eliminarVinculoIndustria
);
router.get("/:empCod/idiomas", empleadosController.listarIdiomasEmpleado);
router.post("/:empCod/idiomas", empleadosController.crearIdiomaEmpleado);
router.patch(
  "/:empCod/idiomas/:idEmpleadoIdioma",
  empleadosController.actualizarIdiomaEmpleado
);
router.delete(
  "/:empCod/idiomas/:idEmpleadoIdioma",
  empleadosController.eliminarIdiomaEmpleado
);
router.get(
  "/:empCod/competencias-digitales",
  empleadosController.listarCompetenciasDigitales
);
router.post(
  "/:empCod/competencias-digitales",
  empleadosController.crearCompetenciaDigital
);
router.patch(
  "/:empCod/competencias-digitales/:idEmpleadoCompetenciaDigital",
  empleadosController.actualizarCompetenciaDigital
);
router.delete(
  "/:empCod/competencias-digitales/:idEmpleadoCompetenciaDigital",
  empleadosController.eliminarCompetenciaDigital
);
router.get(
  "/:empCod/metodologias-activas",
  empleadosController.listarMetodologiasActivasEmpleado
);
router.post(
  "/:empCod/metodologias-activas",
  empleadosController.crearMetodologiaActivaEmpleado
);
router.patch(
  "/:empCod/metodologias-activas/:idEmpleadoMetodologiaActiva",
  empleadosController.actualizarMetodologiaActivaEmpleado
);
router.delete(
  "/:empCod/metodologias-activas/:idEmpleadoMetodologiaActiva",
  empleadosController.eliminarMetodologiaActivaEmpleado
);
router.get(
  "/:empCod/plataformas-virtuales",
  empleadosController.listarPlataformasVirtualesEmpleado
);
router.post(
  "/:empCod/plataformas-virtuales",
  empleadosController.crearPlataformaVirtualEmpleado
);
router.patch(
  "/:empCod/plataformas-virtuales/:idEmpleadoPlataformaVirtual",
  empleadosController.actualizarPlataformaVirtualEmpleado
);
router.delete(
  "/:empCod/plataformas-virtuales/:idEmpleadoPlataformaVirtual",
  empleadosController.eliminarPlataformaVirtualEmpleado
);
router.get(
  "/:empCod/preferencias-docencia",
  empleadosController.listarPreferenciasDocencia
);
router.post(
  "/:empCod/preferencias-docencia",
  empleadosController.crearPreferenciaDocencia
);
router.patch(
  "/:empCod/preferencias-docencia/:idEmpleadoPreferenciaDocencia",
  empleadosController.actualizarPreferenciaDocencia
);
router.delete(
  "/:empCod/preferencias-docencia/:idEmpleadoPreferenciaDocencia",
  empleadosController.eliminarPreferenciaDocencia
);
router.get("/:empCod", empleadosController.obtenerPorCodigo);

module.exports = router;
