CREATE TABLE TB_LogAuditoria (
  IdLogAuditoria bigint unsigned NOT NULL AUTO_INCREMENT,
  Modulo varchar(100) NOT NULL,
  Accion varchar(50) NOT NULL,
  MetodoHttp varchar(10) NOT NULL,
  Ruta varchar(255) NOT NULL,
  CodigoEmpleado varchar(20) NULL,
  IdRegistro varchar(100) NULL,
  UsuarioIdentificador varchar(150) NULL,
  UsuarioNombre varchar(150) NULL,
  UsuarioEmail varchar(150) NULL,
  TipoAutenticacion varchar(30) NULL,
  EstadoHttp smallint unsigned NOT NULL,
  Exitoso tinyint(1) NOT NULL DEFAULT 1,
  DireccionIp varchar(45) NULL,
  UserAgent varchar(255) NULL,
  QueryParamsJson json NULL,
  BodyJson json NULL,
  MetadataJson json NULL,
  FechaCreacion datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (IdLogAuditoria),
  KEY IX_TB_LogAuditoria_FechaCreacion (FechaCreacion),
  KEY IX_TB_LogAuditoria_CodigoEmpleado (CodigoEmpleado),
  KEY IX_TB_LogAuditoria_Modulo_Accion (Modulo, Accion),
  KEY IX_TB_LogAuditoria_UsuarioIdentificador (UsuarioIdentificador)
);
